#!/usr/bin/env zsh
# vim:set expandtab shiftwidth=4 filetype=zsh:
# SPDX-License-Identifier: GPL-3.0-only

#
#
# ~chewygumxx/dotfiles.git
# ::: :/home/dot_config/zsh/wrap/claude
#
#

#
# Wrapper function as configuration
#
# `claude doctor`
# https://code.claude.com/docs/en/settings
# https://code.claude.com/docs/en/cli-reference
#

(( $+commands[claude] )) || return 127

local __this_file="${(D)${${(%):-%N}:A}}"


# ------------
# Directories
# ------------

local -x CLAUDE_CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/claude-code}"
if [[ ! -d "$CLAUDE_CONFIG_DIR" ]]; then
    mkdir -p "$CLAUDE_CONFIG_DIR" || return 1
fi

project_dir() {
    local git_repo_{url,slug}
    git_repo_url="$(git -C "$git_repo_root" remote get-url origin)" || return 1
    git_repo_slug="${${${${${(s:/:)git_repo_url}[-2,-1]}##*:}// /_}%\.git}"
    print "$git_repo_slug"
}

if [[ ! -v CLAUDE_CODE_PROJECT_DIR_NAME ]]; then
    local project_dir
    if project_dir="$(project_dir)"; then
        local -x CLAUDE_CODE_PROJECT_DIR_NAME="$project_dir"
    fi
fi


# ----------
# Utilities
# ----------

if (( $+commands[rg] )); then
    : "${USE_BUILTIN_RIPGREP:=0}"
fi


# ----------
# Telemetry
# ----------

: "${DO_NOT_TRACK:=1}"
: "${DISABLE_TELEMETRY:=1}"
: "${DISABLE_GROWTHBOOK:=1}"
: "${CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC:=1}"


# --------
# Execute
# --------

command claude "$@"
