#!/usr/bin/env zsh
# vim:set expandtab shiftwidth=4 filetype=zsh:
# SPDX-License-Identifier: GPL-3.0-only

#
#
# ~chewygumxx/zsh-config.git
# ::: :/wrap/jq
#
#

#
# Wrapper function for `jq` JSONquery utility
# Currently, this exists entirely for default `--indent 4`
#

(( $+commands[jq] )) || return 127


if ! (( $+@[--indent] )); then
    command jq --indent 4 "$@"
else
    command jq "$@"
fi
